
tasks:
  - init: npm install
    command: export HMR_HOST='gp url 3000' && npm run dev
ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - svelte.svelte-vscodeo your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
#- init: npm install && npm run build
#command: npm run dev
