import { pgTable, serial, date, text, boolean, integer, timestamp, real, varchar, pgEnum } from 'drizzle-orm/pg-core'

export const RR = pgTable('kpt_srm_rr', {
  id: integer('id').primaryKey(),
  division_name: varchar('division_name'),
  vendor_no: varchar('vendor_no'),
  supplier_name: varchar('supplier_name'),
  part_no: varchar('part_no'),
  part_desc: varchar('part_desc'),
  blanket_po: varchar('blanket_po'),
  // blanket_line: varchar('blanket_line '),
  po_date: varchar('po_date'),
  da_no: varchar('da_no'),
  da_date: varchar('da_date'),
  da_qty: integer('da_qty'),
  invoice_no: varchar('invoice_no'),
  gr_no: varchar('gr_no'),
  gr_date: varchar('gr_date'),
  rr_no: varchar('rr_no'),
  rr_date: varchar('rr_date'),
  rr_qty: integer('rr_qty'),
  accepted_qty: integer('accepted_qty'),
  rej_qty: integer('rej_qty'),
  rew_qty: integer('rew_qty'),
  paid_amount: integer('paid_amount'),
  payment_date: varchar('payment_date'),
  reason: varchar('reason'),
  rr_status: varchar('rr_status'),
  landed_cost: integer('landed_cost'),
  // unit_price: integer('unit_price'),
  // received_qty: integer('received_qty'),
  // desp_qty: integer('desp_qty'),
  vendor_remark: varchar('vendor_remark'),
  hal_remark: varchar('hal_remark'),
  // createdAt: timestamp('created_at', {
  // 	precision: 6,
  // 	withTimezone: true,
  // }).defaultNow(),
  // updatedAt: timestamp('updated_at', {
  // 	precision: 6,
  // 	withTimezone: true,
  // }).defaultNow(),
})
